### ISSUE TITLE
Use this plugin, store become not right

### ISSUE THREAD

**Issue by cheft** [mobxjs/babel-plugin-mobx-deep-action#10]
Use this plugin, store become not right, as the picture shows:
![a](https://user-images.githubusercontent.com/1567209/30574177-e46921da-9d2a-11e7-94a9-ec2bacf9bb2c.png)

If you do not use this plugin, this is actually the case:
![b](https://user-images.githubusercontent.com/1567209/30574208-0fb4e0e0-9d2b-11e7-8b90-d6e1b210ec1c.png)

**Comment by Strate** [comment]
@cheft I need reproduceable case.

**Comment by cheft** [comment]
Look [RNMobxTest](https://github.com/cheft/RNMobxTest), thanks!

**Comment by Strate** [comment]
@cheft sorry, but there is too much code. Could you please extract more narrow case?

**Comment by cheft** [comment]
see this file [counter.js](https://github.com/cheft/RNMobxTest/blob/master/src/stores/counter.js)

```js
  @observable count = 0;
```

replace

```js
  constructor() {
    extendObservable(this, {
      count: 0
    })
  }
```

replace  is ok, but not what I want

**Comment by cheft** [comment]
I resolved, this config such:

```js
{
  "passPerPreset": true,
  "presets": [
    {
      "plugins": ["transform-regenerator"]
    },
    {
      "plugins": ["mobx-deep-action"]
    },
    {
      "plugins": ["transform-decorators-legacy", "transform-class-properties"]
    },
    "react-native"
  ]
}

```
