### ISSUE TITLE
README clarification(s)

### ISSUE THREAD

**Issue by EyalPerry** [mobxjs/babel-plugin-mobx-deep-action#11]
1)The README.md file states that 'transform-regenerator' must be applied before this plugin.
It also states that the means to achieve this is by stating this plugin before transform-regenerator.
The babel documentation, on the other hand- states that presets are processed in reverse order.
This needs clarification.

2) Is there any reason I can not just use the plugins section, instead of wrapping the plugins in preset like object literals?
I think if there is one, it should be mentioned in the readme file as well

**Comment by Strate** [comment]
This is related to #12, resolving that issue should simplify plugin setup and readme too.

**Comment by Strate** [comment]
Closed in favor of new plugin https://github.com/Strate/babel-plugin-mobx-async-action
