### ISSUE TITLE
Transform async actions to asyncAction from mobx-utils

### ISSUE THREAD

**Issue by Strate** [mobxjs/babel-plugin-mobx-deep-action#12]
There is a good way to support async actions like this:

```ts
action(async function() {
  await a();
  await b();
})
```

just transform it to:

```ts
import {asyncAction} from "mobx-utils"

asyncAction(function* () {
  yield a();
  yield b();
})
```

Transformation is simple and can be run on any stage of babel.

**Comment by atroberg** [comment]
What is the status of this issue, is it progressing?

**Comment by khomyakov42** [comment]
What progress?

**Comment by Strate** [comment]
Finally, I found time to solve this issue. But as separated plugin: https://github.com/Strate/babel-plugin-mobx-async-action
